#!/bin/bash

# Create output directory if it doesn't exist
mkdir -p /Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed

# Copy and rename files
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 2_ Core Theory/0201thealgorithm.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/the_algorithm.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 2_ Core Theory/0202CardinalSins.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/cardinal_sins.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 2_ Core Theory/0203craftingcompellinghooks.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/crafting_compelling_hooks.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 2_ Core Theory/0204scriptingfundamentals.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/scripting_fundamentals.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 3_ Understanding Platforms/0301helpful formats.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/helpful_formats.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 3_ Understanding Platforms/0302 metrics that matter.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/metrics_that_matter.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 3_ Understanding Platforms/0303buildingyourcontentstrategy.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/building_your_content_strategy.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 4_ Advanced Theory/0401AdvancedMetrics.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/advanced_metrics_analytics.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 4_ Advanced Theory/0402complexformats.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/using_complex_formats.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 4_ Advanced Theory/0403datalediteration.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/data_led_iteration.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 4_ Advanced Theory/0404managingcomments.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/managing_comments.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 4_ Advanced Theory/0405PR.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/pr_who_are_you.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 5_ Advanced Scriptwriting/0501 Emotional Positioning.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/emotional_positioning_for_impact.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 5_ Advanced Scriptwriting/0502NuancedHooks.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/using_nuanced_hooks.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 5_ Advanced Scriptwriting/0503ScriptingforAuthority.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/scripting_for_authority.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 5_ Advanced Scriptwriting/0504scriptwastery.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/script_mastery.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 6_ Technical Mastery/0601ShootingforShortForm.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/shooting_for_short_form.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 6_ Technical Mastery/0603fidelity.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/content_fidelity.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 6_ Technical Mastery/0604ResearchandWriting.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/research.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 7_ Creative Efficiency/0701Repurposing.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/repurposing.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 7_ Creative Efficiency/0702serialisation.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/serialisation.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 8_ Building a Business/0801PostingandScheduling.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/posting_and_scheduling.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 8_ Building a Business/0802buildingyourfunnel.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/building_your_funnel.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 8_ Building a Business/0803delegation.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/team_building_delegation.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 8_ Building a Business/0804monetisation.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/monetisation_evolving.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/JodenExplain0.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/big_picture.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Section 1_ The Fundamentals/0102 Understanding The Frame.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/understanding_the_frame.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/ShootingConfidence.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/camera_confidence.webp"
cp "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/Basicedits0.webp" "/Users/jodennewman/Documents/Code/REACT/ViteTailwindGsap/ReactWebDev/assets/main/DataBaseThumbnails/renamed/editing.webp"

echo "All files have been copied and renamed to the 'renamed' directory."